### ISSUE TITLE
Notice: Undefined index: tmp_path

### ISSUE THREAD

**Issue by ghost** [ZendExperts/phpids#1]
Hi there,

Notice: Undefined index: tmp_path in vendor\ZendExperts\phpids\lib\IDS\Monitor.php on line 217

Notice: Undefined index: tmp_path in vendor\ZendExperts\phpids\lib\IDS\Monitor.php on line 221
Please make sure the folder is writable

**Comment by cosmin-harangus** [comment]
Hello,

Did you receive this notice when installing the ZeSecurity library or the phpids library standalone? This library is just a mirror for the PHPIDS(http://www.phpids.org) library. Any issues related to this code should be redirected to them. If you encountered the problem while using ZeSecurity then please let me know and also add the issue there.

Thanks

**Comment by ghost** [comment]
Hi i received this notice when installing ZeSecurity.

**Comment by cosmin-harangus** [comment]
This should be fixed in the latest version of ZeSecurity
