### ISSUE TITLE
Different basepath to ze-security

### ISSUE THREAD

**Issue by lampi87** [ZendExperts/phpids#3]
Hi!

Within composer, the ze-security package is stored under zendexperts/ze-security. This required package is stored under ZendExperts/phpids. Is it possible to change one directory to merge this packages into one folder?

**Comment by cosmin-harangus** [comment]
Hi,
The ZeSecurity module will soon be updated to use the official phpids library available on github, therefore this mirror will become deprecated.
Please update your dependencies once the changes have been integrated in the ZeSecurity module.

**Comment by lampi87** [comment]
Thanks!
